# Generated by Django 5.1.4 on 2025-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variatons',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
