# Generated by Django 5.1.4 on 2025-01-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variatons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variatons',
            new_name='variations',
        ),
    ]
